CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(511) NOT NULL,
    email VARCHAR(255) NOT NULL,
    registration_date  TIMESTAMP NOT NULL,
    password VARCHAR(255) NOT NULL
);