name: oxygen-account

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17 and Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          maven-version: '2.1.1'
          distribution: 'temurin'
      - name: Build with Maven
        run: |
          cd oxygen-account
          mvn --batch-mode --update-snapshots package
