name: Build and Test

 

on:
  push:
    branches:
      - main

 

jobs:
  build-and-test:
    runs-on: windows-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'

 

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'
        maven-version: '3.8.3'

 

    - name: Build and Test
      run: mvn clean test
