name: Build and Test

on:
  push:
    branches:
      - github-actions-branch

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
        maven-version: '3.9.2'

    - name: Get pom.xml
      run: |
        curl -o pom.xml https://github.com/oxygenxml-incubator/oxygen-account/blob/main/oxygen-account/pom.xml
    - name: Build and Test
      run: mvn clean test
