name: Build and Test

 

on:
  push:
    branches:
      - github-actions-branch

 

jobs:
  build-and-test:
    runs-on: windows-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17

 

    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: 17
        maven-version: '4.0.0'

 

    - name: Build and Test
      run: mvn clean test
