name: Java CI with Maven

on:
  push:
    branches: 
	- main
  pull_request:
    types: [opened, synchronized, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file oxygen-account/pom.xml

    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: oxygen-account/target/*.jar
