name: Java CI with Maven
on:
  push:
    branches:  main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0 
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'
    - name: Cache SonarCloud Packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: $${{ runner.os }}-sonar
    - name: Build with Maven
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn clean -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=oxygen-account --file oxygen-account/pom.xml
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: oxygen-account/target/*.jar
        
  frontend-tests-and-bundle:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Install dependencies
      run: cd oxygen-account-frontend && npm install
    - name: Run frontend tests
      run: cd oxygen-account-frontend && npm test
    - name: Build frontend bundle
      if: success()
      run: cd oxygen-account-frontend && npx webpack
