name: Java CI with Maven

on:
  push:
    branches: [ oxygen-account-branch ]
  pull_request:
    branches: [ oxygen-account-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Test with Maven
      run: mvn test --file pom.xml

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: target/*.jar
